In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [5]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()


layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-10, grad_fn=<MeanBackward0>)

In [11]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units))
    def forward(self, X):
        linear = torch.matmul(X, self.weight) + self.bias
        return F.relu(linear)

In [12]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.6724,  0.2919, -1.7462],
        [ 0.3553,  0.6318, -1.1126],
        [-0.2213, -0.6205,  2.3741],
        [ 1.0190,  1.6215,  0.4519],
        [ 0.6973,  0.3520, -0.1389]], requires_grad=True)

In [13]:
linear(torch.randn(2, 5))

tensor([[0.0000, 0.0000, 4.3389],
        [0.0897, 0.0000, 0.5053]], grad_fn=<ReluBackward0>)

In [14]:
net = nn.Sequential(MyLinear(64,8), MyLinear(8,1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]], grad_fn=<ReluBackward0>)