In [1]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4,8), nn.ReLU(), nn.Linear(8,1))

X = torch.rand(size=(2,4))

net(X)

tensor([[-0.4516],
        [-0.4151]], grad_fn=<AddmmBackward0>)

In [2]:
print(net[2].state_dict())

OrderedDict({'weight': tensor([[-0.1970, -0.2623,  0.3309, -0.2581, -0.0636,  0.3132, -0.2103,  0.2766]]), 'bias': tensor([-0.1470])})


In [3]:
def init_normal(M):
    if type(M) == nn.Linear:
        nn.init.normal_(M.weight, mean=0, std=0.1)
        nn.init.zeros_(M.bias)

net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([ 0.0245,  0.0561,  0.1438, -0.0286]), tensor(0.))

In [5]:
def init_constant(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 1)
        nn.init.zeros_(m.bias)

net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))