In [1]:
import torch

In [9]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [10]:
x.requires_grad_ (True)
x.grad

In [11]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [13]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [14]:
x.grad == 4*x

tensor([True, True, True, True])